#!/bin/bash
echo "in order to run this script you need to install some tools"
url=$1

echo "subdomain enumeration and brute force"
touch subdomains1.txt subdomains.txt
/opt/dnscan/dnscan.py -d %%.$1 -n -N | tee -a subdomains1.txt
assetfinder $1 | tee -a subdomains1.txt
amass enum -d $1 -passive | tee -a subdomains1.txt 

cat subdomains1.txt |sort -u | grep ".$1"| sed '/ /d' > subdomains.txt
rm subdomains1.txt


echo "alive subdomains"
touch alivesubs.txt
cat subdomains.txt | httprobe > alivesubs.txt


echo "pull out the ips and delete https/http"
cat alivesubs.txt | sed 's|http://||g' | sed 's|https://||g' | sort -u > newalivesubs.txt
dig -f newalivesubs.txt +short | sort -u | sed '/[a-z]/d' > ips.txt
rm newalivesubs.txt

echo "scan for ports"
touch scannedsubs.txt
nmap -iL ips.txt -T4 -F -oA scannedsubs.txt
rm ips.txt
